Store MAAS rack ID in maas_rack_id config key.

diff --git a/import-boot-resources b/import-boot-resources
--- a/import-boot-resources
+++ b/import-boot-resources
@@ -32,4 +32,9 @@ function get_rack_id {
 echo ""
 echo "Waiting for rack to import boot resources..."
 RACK_ID=$(get_rack_id)
-aoi-ssh $INSTANCE "while [ \"\$(maas $PROFILE rack-controller list-boot-images $RACK_ID | jq --raw-output '.status' 2> /dev/null)\" != \"synced\" ]; do sleep 0.5; done"
+if [ "$RACK_ID" == "" ]; then
+    echo "Error: could not determine MAAS rack ID."
+    exit 1
+fi
+aoi config set maas_rack_id "$RACK_ID"
+aoi-ssh $INSTANCE "while [ \"\$(maas $PROFILE rack-controller list-boot-images $RACK_ID | jq --raw-output '.status' 2> /dev/null)\" != \"synced\" ]; do sleep 5; done"
